### ISSUE TITLE
Text-area and html editor

### ISSUE THREAD

**Issue by denniscastro** [fhwang/admin_assistant#1]
HIi.. good plugin...

I have a question..

I have text-area inputs and htmls editor like fck-editor and mce editor... this plugin allow use html editor and config it???

Dennis Castro.

**Comment by fhwang** [comment]
There is no built-in rich-text editor, but you should be able to add it yourself fairly easily.

Check out this part of the API docs: http://fhwang.github.com/admin_assistant/api/form.html#partials

You can write partials that substitute for the column edit area, or go after the column edit area. So you should be able to make a partial like app/views/admin/blog_posts/_body_input.html.erb that would include something like MCE Editor for you.

**Comment by denniscastro** [comment]
Hi.. 

Ok. I understand... I'll try it this week..

Thanks a lot.
Dennis Castro
