### ISSUE TITLE
Rails 3.1 support?

### ISSUE THREAD

**Issue by rsanheim** [fhwang/admin_assistant#10]
Any testing done with Rails 3.1?  Looks like this is a nice alternative to some of the more 'full stack' scaffolds, but I don't see mention of rails 3.xx support in the readme.

**Comment by fhwang** [comment]
Right this moment, admin_assistant supports Rails 3.0.x. 3.1 support is planned but it might take a week or so to get to it. I'll keep you posted on this issue.

**Comment by fhwang** [comment]
Actually, I was able to get to that sooner than I thought. AA 2.1.0, just released, should be able to work with Rails 3.1. A caveat: I'm not personally using Rails 3.1 yet. Can you give it a try and let me know if you hit any issues?

**Comment by rsanheim** [comment]
Hey Francis

Just tried in an app that has been using 3.1RC5 with the asset pipeline.  Everything went fine until Rails tried to render `admin_assistant_includes` - the admin_assisstant css, js, and images all rendered 404.

I see you are using the asset style ActiveScaffold did of copying assets over to the main app folder.  I'm not sure that  will play nice with 3.1 apps using the asset pipeline....

**Comment by fhwang** [comment]
Yeah, that would probably be a problem ... let me look into a fix.

**Comment by fhwang** [comment]
So, admin_assistant 2.2.1 has assets positioned so they can be used in Sprockets manifest files. There's more info here: http://fhwang.github.com/admin_assistant/quick_start.html

Please give it a try and let me know if you see other issues.

**Comment by rsanheim** [comment]
Thanks Francis, hope to try this again later this week.

**Comment by rsanheim** [comment]
Awesome , got the assets working!  Now things appear to work, though I see issue #11 now where there are no action links, just the index view.  Anything in particular I should look into or trace to help track this down?

**Comment by fhwang** [comment]
Sorry for the late reply, somehow I missed this in my inbox.

As for issue #11, I think we should close this issue, and then you can follow on to issue #11 in the interest of consolidating work ... between you and cacciatc hopefully we can figure out how to duplicate it.
