### ISSUE TITLE
FileColumn Support?

### ISSUE THREAD

**Issue by a9k** [fhwang/admin_assistant#16]
Is there really FileColumn support?
I see the support for Paperclip but not FileColumn in the source but maybe there is some hidden magic I missed.

I have a FileColumn that is recordings of lectures (mp3s) not pictures.
AdminAssistant edit forms just show a text input box for that file_column - no upload button.

**Comment by fhwang** [comment]
Yeah, sorry, that was an outdated README. It used to support FileColumn but that was some time ago. When I moved to Rails 3 I removed FileColumn because it was pretty un-maintained and not working with Rails 3 anyway.
