### ISSUE TITLE
Need to push gem to RubyGems.org

### ISSUE THREAD

**Issue by coreyti** [fhwang/admin_assistant#2]
Hi,

While your gemspec here (on github) references "will_paginate":

```
s.add_dependency 'will_paginate'
```

the version hosted on RubyGems.org still references "mislav-will_paginate":

```
$ gem specification -r admin_assistant
--- !ruby/object:Gem::Specification 
name: admin_assistant
version: 1.0.0
...
dependencies: 
- !ruby/object:Gem::Dependency 
  name: mislav-will_paginate
```

resulting in:

```
$ gem install admin_assistant
ERROR:  Error installing admin_assistant:
       admin_assistant requires mislav-will_paginate (>= 0, runtime)
```

It would be great if the current (err, same version-numbered) gem could be pushed to RubyGems.

Thanks,
Corey

**Comment by fhwang** [comment]
Hi Corey,

I've updated the gem dependency and pushed to rubygems.org.

Francis

**Comment by coreyti** [comment]
Nice!  Thanks.
