### ISSUE TITLE
Joining User Defined Links on Index views with &bull; 

### ISSUE THREAD

**Issue by nodanaonlyzuul** [fhwang/admin_assistant#20]
Hey Francis - what's up with this line?

https://github.com/fhwang/admin_assistant/blob/44d277c97c8d86f6a0cea51f7dd55937c947f9ac/lib/admin_assistant/index.rb#L290

It ends up dumping bullet points into the markup...not wrapped in any tags so it's hinky to remove via CSS.

![screen shot 2013-08-13 at 6 33 10 pm](https://f.cloud.github.com/assets/8731/958599/f7d2192a-0468-11e3-82eb-aa864976ba4e.png)

**Comment by fhwang** [comment]
I could wrap it in a span tag, would that fix your issue?

**Comment by nodanaonlyzuul** [comment]
Oh - sure - I guess you could wrap in a classed span this way its mark is a little less invasive and devs can choose how/if they would style it.

**Comment by nodanaonlyzuul** [comment]
Orrrr - just `join(" ")` - and let people who want to customize styles target those anchor tags directly.
Maybe that seems least intrusive.

**Comment by fhwang** [comment]
Should be fixed in 2.3.1 now, let me know.

**Comment by nodanaonlyzuul** [comment]
Totally awesome. Thanks man.
