### ISSUE TITLE
Can't search non boolean VirtualColumns.

### ISSUE THREAD

**Issue by nodanaonlyzuul** [fhwang/admin_assistant#22]
Bear with me...

Let's say:
- A User `has_one :address_information`
  
  *\* AddressInformation has a 'street_name' column.
- In my contrived Users#index example we want to search by users' street_names...

```
admin_assistant_for User do |a|
  a.index do |index|
    index.include [:address_information]

    index.columns :name, :login, :email

    index.search do |search|
      search.columns :street_name
      search[:street_name].conditions do |street_name|
        "address_informations.street_name like '#{street_name}%'" if street_name
      end
    end

  end

end
```

RIght now you can't do this - and I'm pretty sure it has to do with the [implementation of attributes_for_search_object()](https://github.com/fhwang/admin_assistant/blob/master/lib/admin_assistant/virtual_column.rb#L16) 

If a string that isn't "true" gets passed in as a param then the `conditions` block in the controller is never going to get a value.

I think you solve this and not break other stuff by changing attributes_for_search_object's implementation to...

```
    def attributes_for_search_object(search_params, compare_to_range)
      value = (search_params[@name.to_s].blank? || search_params[@name.to_s] == 'false') ? false : search_params[@name.to_s]
      {@name => value}
    end
```

**Comment by nodanaonlyzuul** [comment]
Oh sorry - this issue was discovered while using version 2.3.1

**Comment by fhwang** [comment]
Actually, let me bring up another possibility: For `has_many` relations, you can use `match_text_fields_for_association`, which automatically searches all strings and text fields on the associated table:

```
admin_assistant_for User do |a|
  a.index.search do |search|
    search.columns :blog_posts
    search[:blog_posts].match_text_fields_for_association
  end
end
```

That won't work for your `address_information` example, because it's a `has_one`, but it should be easy enough to add.

Would you prefer that? Or would you rather have the option of selecting which specific fields on `address_information` to match?

**Comment by nodanaonlyzuul** [comment]
I can see how adding the ability to call `match_text_fields_for_association` on a has_one relationship would be useful but my real-world need requires that I have form fields to query individual columsn/attributes in the class on the right-hand side of my `has_one` relationship.
If you don't mind my implementation above, I don't mind rocking a pull request.

Also, Happy Thanksgiving Francis - I respect your commitment to GitHub Flavored Markdown, more people should follow your example.

**Comment by fhwang** [comment]
A pull request would be great, if you can submit it with a test case. Or, I don't mind making the change myself.

**Comment by nodanaonlyzuul** [comment]
You've got me - I'm overwhelmed by your test setup.
If you do the change I'd be happy to take a look at how you tested it so I can better contribute in the future.

**Comment by fhwang** [comment]
Yah, you're not the only person who's told me the test setup is wonky. Lemme do the fix.

**Comment by fhwang** [comment]
Please give this a try with version 2.4.0.

**Comment by nodanaonlyzuul** [comment]
Many thanks! So far - so good. :tulip:
