### ISSUE TITLE
[column]_string functionality not working

### ISSUE THREAD

**Issue by alexfarrill** [fhwang/admin_assistant#4]
I find that it affects the index view but not the form view

> > [column]_string

If this helper method is present, its returned string will be rendered within a text field. Odds are you’ll use this with the controller method [column]_from_form, above.

def tags_string(blog_post)
  blog_post.tags.map { |tag| tag.tag }.join ' '
end

**Comment by fhwang** [comment]
Alex, I can't see confirm this bug with 1.0.2 and let me know if you're still seeing it?

**Comment by fhwang** [comment]
Sorry, got my wires crossed version-wise -- let me look into this a bit more.

**Comment by fhwang** [comment]
Hey Alex, I can't verify this with either AA1 or AA2 ... can you verify and submit a sample?

**Comment by fhwang** [comment]
Closing for now, please feel free to re-open if you manage to duplicate.
