### ISSUE TITLE
Doesn't work as a gem... at all

### ISSUE THREAD

**Issue by zenspider** [fhwang/admin_assistant#6]
Add admin_assistant to my isolate setup and run `rake environment` to install:

```
7896 % rake environment -t
(in /Users/ryan/Work/git/seattlerb)
[1/1] Isolating admin_assistant (~> 1.0.2).
** Invoke environment (first_time)
** Execute environment
rake aborted!
uninitialized constant AdminAssistant::Request::Base
/Users/ryan/Work/git/seattlerb/tmp/isolate/ruby-1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:440:in `load_missing_constant'
/Users/ryan/Work/git/seattlerb/tmp/isolate/ruby-1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:80:in `const_missing'
/Users/ryan/Work/git/seattlerb/tmp/isolate/ruby-1.8/gems/admin_assistant-1.0.2/lib/admin_assistant/request/update.rb:3
```

There are a number of files that don't require what they need, expecting active_support to do its magic, but it doesn't do magic for gems iirc.

(and I have the same missing file issues as my other ticket)

**Comment by brynary** [comment]
I'm running into this issue as well (using Bundler v1.0.10).

**Comment by fhwang** [comment]
Ryan: I'm unable to duplicate this issue. However, I've never used Isolate so it's entirely possible I'm missing something obvious. Maybe can you attach the config you tried so I can try to duplicate it?

Bryan: If you're still dealing with this, care to file a separate ticket? Thx.

**Comment by fhwang** [comment]
Closing for now: Please feel free to re-open if you can find the time get back with more specific info about how to replicate the issue.
